// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-z5BYl299iTDkjcwZXn9VjLWHqRH2Ac',
    appId: '1:845249555311:web:f49fd02944322ac972d69a',
    messagingSenderId: '845249555311',
    projectId: 'stefan-finki',
    authDomain: 'stefan-finki.firebaseapp.com',
    storageBucket: 'stefan-finki.firebasestorage.app',
    measurementId: 'G-5BPVG78ZGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeO4M5O47S1cqcfS36B8Jd29n39IxwKg',
    appId: '1:845249555311:android:5ed3d01944ef5a1772d69a',
    messagingSenderId: '845249555311',
    projectId: 'stefan-finki',
    storageBucket: 'stefan-finki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3srxWfapA4u3NB7lvehjzqht2POPCszM',
    appId: '1:845249555311:ios:2f8eca8171bfc18e72d69a',
    messagingSenderId: '845249555311',
    projectId: 'stefan-finki',
    storageBucket: 'stefan-finki.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3srxWfapA4u3NB7lvehjzqht2POPCszM',
    appId: '1:845249555311:ios:2f8eca8171bfc18e72d69a',
    messagingSenderId: '845249555311',
    projectId: 'stefan-finki',
    storageBucket: 'stefan-finki.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy-z5BYl299iTDkjcwZXn9VjLWHqRH2Ac',
    appId: '1:845249555311:web:af4d2bd4404d803072d69a',
    messagingSenderId: '845249555311',
    projectId: 'stefan-finki',
    authDomain: 'stefan-finki.firebaseapp.com',
    storageBucket: 'stefan-finki.firebasestorage.app',
    measurementId: 'G-T0RCM8NB4N',
  );

}